// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyK5zZZDqDBkQ2d7TdFF5lfOYzk8F81MM',
    appId: '1:122381905377:web:4fbd097f4d63dc97bc76a0',
    messagingSenderId: '122381905377',
    projectId: 'meapp-1bf91',
    authDomain: 'meapp-1bf91.firebaseapp.com',
    storageBucket: 'meapp-1bf91.firebasestorage.app',
    measurementId: 'G-HYZPDYJT5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CNagaW-kglQjKhDq3lJw6u0V0QVEexg',
    appId: '1:122381905377:android:0c31da9c527bb256bc76a0',
    messagingSenderId: '122381905377',
    projectId: 'meapp-1bf91',
    storageBucket: 'meapp-1bf91.firebasestorage.app',
  );
}
